-- Run once after default-visible-reveal-migration.sql.
-- Guest links are reveal-only, revocable, expiring, and never grant contributor or Studio access.

create table if not exists public.reveal_share_links (
  id uuid primary key default uuid_generate_v4(),
  project_id uuid not null references public.projects(id) on delete cascade,
  token_hash text not null unique check (token_hash ~ '^[a-f0-9]{64}$'),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists reveal_share_links_active_idx
  on public.reveal_share_links (project_id, expires_at desc)
  where revoked_at is null;

create table if not exists public.reveal_share_visits (
  id bigint generated by default as identity primary key,
  share_link_id uuid not null references public.reveal_share_links(id) on delete cascade,
  visited_at timestamptz not null default now(),
  ip_hash text,
  user_agent text
);

create index if not exists reveal_share_visits_link_idx
  on public.reveal_share_visits (share_link_id, visited_at desc);

alter table public.reveal_share_links enable row level security;
alter table public.reveal_share_visits enable row level security;

grant all on public.reveal_share_links to service_role;
grant all on public.reveal_share_visits to service_role;
grant select, insert, update, delete on public.reveal_share_links to authenticated;
grant select on public.reveal_share_visits to authenticated;

drop policy if exists "owner manages reveal share links" on public.reveal_share_links;
grant usage, select on sequence public.reveal_share_visits_id_seq to service_role;
create policy "owner manages reveal share links"
on public.reveal_share_links for all to authenticated
using (public.is_project_owner(project_id))
with check (public.is_project_owner(project_id));

drop policy if exists "owner reads reveal share visits" on public.reveal_share_visits;
create policy "owner reads reveal share visits"
on public.reveal_share_visits for select to authenticated
using (
  exists (
    select 1 from public.reveal_share_links link
    where link.id = share_link_id
      and public.is_project_owner(link.project_id)
  )
);

notify pgrst, 'reload schema';
